version: '3.8'
services:
  database:
    image: postgres:15.5-bullseye
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: factorialdb
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'

  queue:
    image: rabbitmq:3.12-management
    container_name: queue
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "8081:15672"
      - "25676:25676"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'