version: '3.8'
services:
  database:
    image: postgres:15.5-bullseye
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: factorialdb
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    networks:
      - fnet

  queue:
    image: rabbitmq:3.12-management
    container_name: queue
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "8081:15672"
      - "25676:25676"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    networks:
      - fnet

  factorial-service:
    image: calcltda/factorial-service:0.0.1
    container_name: factorial-service
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    depends_on:
      - database
      - queue
    networks:
      - fnet

  factorial-worker:
    image: calcltda/factorial-worker:0.0.1
    container_name: factorial-worker
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    depends_on:
      - database
      - queue
    networks:
      - fnet

networks:
  fnet:

#  pgadmin:
#    image: elestio/pgadmin:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "root@admin.com"
#      PGADMIN_DEFAULT_PASSWORD: "pass"
#      PGADMIN_LISTEN_PORT: 8080
#    ports:
#      - "8080:8080"
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: '512M'
#    depends_on:
#      - database